---
system_common_packages:
  - curl
  - git
  - make
  - pipx
  - python3 # Should already be installed but keeping it here for reference
  - python3-pip
  - stow
  - tmux
  - unzip
  - zsh

system_optional_packages:
  - exa
  - fd-find
  - fzf
  - htop
  - openssh-client
  - python3-venv
  - python3-virtualenv
  - ripgrep
  - bat
